GET http://192.168.71.106:8080/auth/login/user1
Accept: application/json

###
POST http://192.168.71.106:8080/auth/register
Content-Type: application/json

{
  "userId":"user1",
  "userName":"user1",
  "userPassword":"pw12",
  "userEmail":"e1@mail.com"
}

###
